version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser
    restart: always
    container_name: filebrowser
    environment:
      - FB_AUTH_METHOD=default
    ports:
      - "1927:80"
    volumes:
      - ./data:/srv
      - ./filebrowser.db:/database/filebrowser.db # Database untuk menyimpan user dan config
